version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: db
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_ROOT_PASSWORD: "user"
      MYSQL_DATABASE: "lavagna"
      SERVICE_NAME: "db"
    networks:
      - db-net
    volumes:
      - db-vol:/var/lib/mysql
    healthcheck:
      #test: [ "CMD", "mysqladmin", "ping", "-h", "localhost:3306" ]
      #test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb" ]
      test:
        [
          "CMD",
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          #'db:3306/lavagna',
          '-uroot',
          '-puser' #'-p$$MYSQL_ROOT_PASSWORD'
        ]
      interval: 10s
      timeout: 40s
      retries: 10
      start_period: 30s

  lavagna:
    # image: lavagna:6
    build:
      context: .
      dockerfile: Dockerfile.6-aws.2
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-net
      - public-net
    volumes:
      - ./:/lavagna
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://lavagna:8080 || exit
      interval: 5s
      retries: 60
      start_period: 5s
      timeout: 10s

  nginx-shield:
    image: nginx
    ports:
      - 80:80
    networks:
      - public-net
    depends_on:
      lavagna:
        condition: service_healthy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./project/src/main/webapp:/usr/share/nginx

  docs-shield:
    image: nginx
    ports:
      - 8081:80
    networks:
      - public-net
    # depends_on:
    #   lavagna:
    #     condition: service_healthy
    volumes:
      - ./docs-conf/nginx.conf:/etc/nginx/nginx.conf

  docs:
    #image: lavagna:7
    build:
      context: .
      dockerfile: Dockerfile.7
    #hostname: abroad-host
    # ports:
    #   - 8081:45001
    networks:
      - public-net

networks:
  db-net:
  public-net:


volumes:
  db-vol: #external: true
