# FROM maven:3.6.3-openjdk-8 as stage

# COPY project /project

# WORKDIR /project

# RUN mvn verify

FROM openjdk:8-jre-alpine

#COPY --from=stage /project/target /target

ENV DB_DIALECT="MYSQL"
ENV DB_URL="lavagna.csbxzjhemvqj.us-west-2.rds.amazonaws.com"
ENV DB_USER="user"
ENV DB_PASS="useruser"
ENV SPRING_PROFILE="dev"

COPY entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /lavagna/project/target

ENTRYPOINT [ "entrypoint.sh" ]


